version: '3.8'

services:
  ubuntu-server:
    build: .
    container_name: scl-ubuntu-test
    ports:
      - "2222:22"   # SSH
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    hostname: ubuntu-test-server
    networks:
      - scl-network
    volumes:
      - ./shared:/shared  # Shared directory for file transfers
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: unless-stopped

networks:
  scl-network:
    driver: bridge